version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: eslint-plugin-markdown
    versions:
    - 2.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
